### ISSUE TITLE
energy efficiency definition

### ISSUE THREAD

**Issue by marisolpalmero** [billwuqin/draft-bclp-green-terminology#12]
I temp to disagree with this part of the definition for Energy Efficiency:
 
Energy Efficiency: : Refers to the ability to control the use of available energy in an optimized manner (e.g., in a resource conserved manner and at low cost).
 
I agree on how it is addressed in the second paragraph...
 
Energy Efficiency: :  is a ratio between the useful output and input of an energy conversion process of a network, device, or component.

**Comment by boucadair** [comment]
I think this is now fixed in #11

**Comment by boucadair** [comment]
Here is the current entry in the main:

> Energy Efficiency/Energy Efficiency Ratio (EER):
> The energy efficiency is expressed as the ratio between the useful output and input of an energy conversion process of a network, device, or component.
> 
> For instance, in relation with a networking device, it can be stated as the ratio of total throughput (e.g., of a network element capacity) to the total power consumed (bits/Joule).
> 
> This ratio (i.e., Energy Efficiency Ratio, EER) is the throughput forwarded by 1 watt (e.g., [[I-D.cprjgf-bmwg-powerbench](https://billwuqin.github.io/draft-bclp-green-terminology/draft-bclp-green-terminology.html#I-D.cprjgf-bmwg-powerbench)]).
> 
> A higher EER indicates a better energy efficiency.

**Comment by billwuqin** [comment]
@marisolpalmero Let us know whether the change address your comment, 
I think the draft is in good shape for initial submisison.

**Comment by boucadair** [comment]
@billwuqin, I think we are almost  there for -00. We still need some quick fixes (see my PR) + add references for each metric. Once done, we can submit the text. Thanks

**Comment by billwuqin** [comment]
@boucadair PR has been incorporated in and references have been added, see https://github.com/billwuqin/draft-bclp-green-terminology/commit/b1ea497cede88c796317e19c3e100181a7ad2a73

**Comment by billwuqin** [comment]
@boucadair @marisolpalmero @luismcontreras https://datatracker.ietf.org/doc/draft-bclp-green-terminology/, 00 version has been submitted now. Thanks all.
