### ISSUE TITLE
description needs to match the formula

### ISSUE THREAD

**Issue by boucadair** [billwuqin/draft-bclp-green-terminology#17]
https://github.com/billwuqin/draft-bclp-green-terminology/blob/f0fbc34b4964e74482a897b28d5512fba09e9917/draft-bclp-green-terminology.md?plain=1#L244C1-L251C76

There is a disconnect between the notations and the description.

**Comment by billwuqin** [comment]
Implement in https://github.com/billwuqin/draft-bclp-green-terminology/commit/53cbba9aa2d5607d494abed1d6e0220fb665880a

**Comment by boucadair** [comment]
Looks better. Thanks @billwuqin.
