### ISSUE TITLE
Throughput vs NDR

### ISSUE THREAD

**Issue by marisolpalmero** [billwuqin/draft-bclp-green-terminology#20]
In ATIS TEER/ ETSI/ITU, it is not used the formula Ti = a*Tu1 + b*Tu2 + c*Tu3 for the traffic. It is used non-drop-rate

L.1310: title: Energy efficiency metrics and measurement methods for telecommunication equipment target: https://www.itu.int/rec/T-REC-L.1310-202409-P date: 2024

**Comment by boucadair** [comment]
I also see NDR was removed from https://datatracker.ietf.org/doc/html/[draft-ietf-bmwg-mlrsearch-07](https://datatracker.ietf.org/doc/html/draft-ietf-bmwg-mlrsearch-07).  It uses Throughput  as well.

**Comment by williamchern** [comment]
Generally, there are three places where the EER and throughput are defined.

**Comment by boucadair** [comment]
#22

**Comment by billwuqin** [comment]
Addressed in https://github.com/billwuqin/draft-bclp-green-terminology/commit/bef1e5ffc7e18fe1ef4583b722de6cef0f5ef68d, thanks WilliamChern
